--------------------------------------------------------
--  DDL for Table BLOGCOMMENT
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."BLOGCOMMENT" 
   (	"COMMENTID" NUMBER(10,0), 
	"BLOGID" NUMBER(10,0), 
	"COMMENTDATE" TIMESTAMP (6), 
	"COMMENTMESSAGE" VARCHAR2(2000 CHAR), 
	"USERNAME" VARCHAR2(255 CHAR)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
