--------------------------------------------------------
--  Constraints for Table BLOGCOMMENT
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."BLOGCOMMENT" ADD PRIMARY KEY ("COMMENTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."BLOGCOMMENT" MODIFY ("BLOGID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."BLOGCOMMENT" MODIFY ("COMMENTID" NOT NULL ENABLE);
