--------------------------------------------------------
--  DDL for Table BLOG
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."BLOG" 
   (	"BLOGID" NUMBER(10,0), 
	"BLOGCONTENT" VARCHAR2(4000 CHAR), 
	"BLOGTITLE" VARCHAR2(255 CHAR), 
	"CREATEDDATE" TIMESTAMP (6), 
	"DISLIKES" NUMBER(10,0), 
	"LIKES" NUMBER(10,0), 
	"STATUS" VARCHAR2(255 CHAR), 
	"USERNAME" VARCHAR2(255 CHAR)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
