--------------------------------------------------------
--  DDL for Table JOB
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."JOB" 
   (	"JOBID" NUMBER(10,0), 
	"JOBDESCRIPTION" VARCHAR2(2000 CHAR), 
	"JOBDESIGNATION" VARCHAR2(255 CHAR), 
	"JOBPROFILE" VARCHAR2(255 CHAR), 
	"JOBSTATUS" VARCHAR2(255 CHAR), 
	"POSTEDDATE" TIMESTAMP (6), 
	"QUALIFICATIONREQUIRED" VARCHAR2(255 CHAR), 
	"USERNAME" VARCHAR2(255 CHAR)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
